"""Semantic theme aliases for UI-v2."""

from invoice_tool.ui_v2 import tokens as _t

# Colors
COLOR_PRIMARY = _t.ACCENT
COLOR_PRIMARY_HOVER = _t.ACCENT_HOVER
COLOR_PRIMARY_SUBTLE = _t.ACCENT_SUBTLE
COLOR_ACCENT_FAINT = _t.ACCENT_FAINT
COLOR_NAV_ACTIVE_BG = _t.SIDEBAR_ACCENT_BG
COLOR_PAGE_BG = _t.CANVAS
COLOR_SIDEBAR_BG = _t.SIDEBAR_BG
COLOR_SIDEBAR_BORDER = _t.SIDEBAR_BORDER
COLOR_SIDEBAR_TEXT = _t.SIDEBAR_TEXT
COLOR_SIDEBAR_TEXT_HOVER = _t.SIDEBAR_TEXT_HOVER
COLOR_SIDEBAR_TEXT_ACTIVE = _t.SIDEBAR_TEXT_ACTIVE
COLOR_SIDEBAR_GROUP = _t.SIDEBAR_GROUP
COLOR_SIDEBAR_ACCENT_BG = _t.SIDEBAR_ACCENT_BG
COLOR_SIDEBAR_HOVER_BG = _t.SIDEBAR_HOVER_BG
COLOR_SURFACE = _t.SURFACE
COLOR_SURFACE_ELEVATED = _t.SURFACE_ELEVATED
COLOR_SURFACE_ALT = _t.SURFACE_SUBTLE
COLOR_CANVAS = _t.CANVAS
COLOR_TEXT_PRIMARY = _t.INK
COLOR_TEXT_SECONDARY = _t.INK_2
COLOR_TEXT_MUTED = _t.MUTED
COLOR_MUTED_LIGHT = _t.MUTED_LIGHT
COLOR_TEXT_DISABLED = _t.DISABLED
COLOR_BORDER = _t.LINE
COLOR_BORDER_STRONG = _t.LINE_STRONG
COLOR_SUCCESS = _t.SUCCESS
COLOR_SUCCESS_SOFT = _t.SUCCESS_SOFT
COLOR_WARNING = _t.WARN
COLOR_WARNING_SOFT = _t.WARN_SOFT
COLOR_WARN_BORDER = _t.WARN_BORDER
COLOR_ERROR = _t.ERR
COLOR_ERROR_SOFT = _t.ERR_SOFT

# Typography
FONT_PRODUCT_LABEL = _t.FONT_PRODUCT_LABEL
FONT_SIZE_PAGE_TITLE = _t.FONT_PAGE_TITLE
FONT_SIZE_KPI_VALUE = _t.FONT_KPI_VALUE
FONT_SIZE_KPI_VALUE_LONG = _t.FONT_KPI_VALUE_LONG
FONT_SIZE_DETAIL_HEADER = _t.FONT_DETAIL_HEADER
FONT_SIZE_PAGE_DESC = _t.FONT_PAGE_DESC
FONT_SIZE_SECTION_TITLE = _t.FONT_SECTION_TITLE
FONT_SIZE_CARD_TITLE = _t.FONT_CARD_TITLE
FONT_SIZE_BODY = _t.FONT_BODY
FONT_SIZE_METADATA = _t.FONT_METADATA
FONT_SIZE_LABEL = _t.FONT_LABEL
FONT_SIZE_HELPER = _t.FONT_HELPER
FONT_SIZE_STATUS = _t.FONT_STATUS
FONT_SIZE_BUTTON = _t.FONT_BUTTON
FONT_SIZE_NAV_GROUP = _t.FONT_NAV_GROUP
FONT_SIZE_NAV_ITEM = _t.FONT_NAV_ITEM
FONT_SIZE_CAPTION = _t.FONT_STATUS
FONT_SIZE_MONO = _t.FONT_MONO

METADATA_LABEL_WIDTH = _t.METADATA_LABEL_WIDTH

# Spacing
SPACE_XS = _t.SP_4
SPACE_SM = _t.SP_8
SPACE_MD = _t.SP_12
SPACE_LG = _t.SP_16
SPACE_XL = _t.SP_20
SPACE_XXL = _t.SP_24
SPACE_3XL = _t.SP_32
SPACE_4XL = _t.SP_40
SPACE_5XL = _t.SP_48

# Layout
NAV_WIDTH = _t.NAV_WIDTH
APP_MIN_WIDTH = _t.APP_MIN_WIDTH
PRODUCT_DISPLAY_NAME = _t.PRODUCT_DISPLAY_NAME
CONTENT_MAX_WIDTH = _t.CONTENT_MAX_WIDTH
FORM_MAX_WIDTH = _t.FORM_MAX_WIDTH
DETAIL_PANEL_MIN_WIDTH = _t.DETAIL_PANEL_MIN_WIDTH
LIST_PANEL_MIN_WIDTH = _t.LIST_PANEL_MIN_WIDTH
LIST_DETAIL_GAP = _t.LIST_DETAIL_GAP
LIST_DETAIL_MIN_HEIGHT = _t.LIST_DETAIL_MIN_HEIGHT
LIST_DETAIL_EDIT_HEIGHT = _t.LIST_DETAIL_EDIT_HEIGHT
LIST_DETAIL_MAX_HEIGHT = _t.LIST_DETAIL_MAX_HEIGHT
INPUT_CONTROL_HEIGHT = _t.INPUT_CONTROL_HEIGHT
WORKFLOW_PANEL_MIN_HEIGHT = _t.WORKFLOW_PANEL_MIN_HEIGHT
COMPACT_CARD_MIN_WIDTH = _t.COMPACT_CARD_MIN_WIDTH
WORKFLOW_CARD_HEIGHT = 280

# Radius
RADIUS_INPUT = _t.RADIUS_INPUT
RADIUS_BUTTON = _t.RADIUS_BUTTON
RADIUS_CARD = _t.RADIUS_CARD
RADIUS_PANEL = _t.RADIUS_PANEL

PANEL_PADDING = SPACE_XL
PAGE_PADDING = SPACE_3XL
